spring.application.name=workshop_zepcla

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=workshop_zecla
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
#
# spring.datasource.url=jdbc:postgresql://db.cvuquyxdaacoubuazrbm.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=workshop2026-ifa
#
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
jwt.secret=une_cle_super_longue_pour_jwt_256_bits_minimum
jwt.expiration=3600000
